[package]
name = "surrealdb"
publish = false
edition = "2021"
version = "0.0.0"
authors = ["Tobie Morgan Hitchcock <tobie@surrealdb.com>"]

[profile.release]
lto = true
strip = true
opt-level = 'z'
panic = 'abort'
codegen-units = 1

[lib]
name = "surrealdb"
crate-type = ["cdylib"]

[dependencies]
chrono = { version = "0.4.24", features = ["serde", "wasmbind"] }
fern = "0.6.2"
getrandom = { version = "0.2.9", features = ["js"] }
js-sys = "0.3.61"
log = "0.4.17"
thiserror = "1.0.40"
wasm-bindgen = { version = "0.2.84", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.34"
web-sys = { version = "0.3.61", features = ["console"] }

[dependencies.surrealdb]
version = "1.0.0-beta.9"
path = "../surrealdb/lib"
default-features = false
features = [
	"kv-mem",
	"kv-indxdb",
	"protocol-http",
	"protocol-ws",
	"rustls",
	"http",
]
